spring.application.name=instaChatAuto
instagram.webhook.verify-token=${INSTAGRAM_WEBHOOK_VERIFY_TOKEN}
instagram.access-token=${INSTAGRAM_ACCESS_TOKEN}
INSTAGRAM_ACCOUNT_ID=${INSTAGRAM_ACCOUNT_ID}
server.port=${PORT:8080}


spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.8-flash
spring.ai.google.genai.chat.temperature=0.7